### ISSUE TITLE
Program does not download full art

### ISSUE THREAD

**Issue by VanTuz5** [sentouki/Artify#1]
The program does not download the full version of the art, but its reduced version

**Comment by sentouki** [comment]
on which platform? and which art? a link would be helpful i could try it out myself

**Comment by VanTuz5** [comment]
Sorry, I completely forgot to write that the program did not download full art from deviantart.
Platform - windows 10. Artist - https://www.deviantart.com/dream-and-nightmare

**Comment by sentouki** [comment]
Thank you for submitting the issue, you were right, the app indeed downloaded the scaled down versions of the images. I assumed that the list deviantart api gives me contains the urls to the original sized images, which is the case for the most images but some images seem to be an exception (e.g. ultra wide images/banner).
I've fixed it in my latest [commit](https://github.com/sentouki/Artify/commit/5d5f7590e77b0f3e3f3ceeafbc885a16da887926)
